### PR TITLE
update to angular 6

### PR DESCRIPTION
**Pull request by rars**
Fixes issue #90

### CODE REVIEW

**Comment by rars** [comment]
Hi @PillowPillow. Please could you take a look at this PR when you get a chance?

**Comment by davidkarlsen** [comment]
@PillowPillow any chance to merge?

**Comment by owen26** [comment]
It would be awesome to get it merged.

**Comment by Hadev-JHH** [comment]
sure hope this gets merged in soon.

**Comment by owen26** [comment]
It's sad to see a good library like this no longer updating anymore.

**Comment by rars** [comment]
@thetric I've published as `@rars/ngx-webstorage` 3.0.0 for anyone that wants to use this. Let me know if you have any problems.

Would still like to get this merged into `ngx-webstorage` if possible to avoid having to use a fork though.

**Comment by coffeetea-synchestra** [comment]
@PillowPillow  thx!

ps.: still waiting for merge :)

**Comment by ben-henoida** [comment]
@rars 
Thank you for forking this project, I have been waiting for the angular 6 upgrade desesperately !
are you planning to publish the new version on npm ? If you do can you enable 'issues' on your project ? Many thanks

**Comment by rars** [comment]
Hi @ben-henoida 
Thanks. I've enabled 'Issues' on the repo. Not sure what you mean regarding publishing the new version on npm. I've already published to npm the Angular 6 version as @rars/ngx-webstorage (https://www.npmjs.com/package/@rars/ngx-webstorage).

You should be able to install as `npm install @rars/ngx-webstorage`. I don't think I can update the `ngx-webstorage` version on npm as I won't have permission.

**Comment by ben-henoida** [comment]
Thank you again @rars, my bad, I had not found @rars/ngx-webstorage  on npmjs...

I have created a pull request on your project to update the doc
For instance change
    Download the library using npm npm install --save ngx-webstorage
To
    Download the library using npm npm install --save @rars/ngx-webstorage

**Comment by alundiak** [comment]
I'm interested in Angular 7.x support. Will this PR/code changes be enough? 

cc/ @rars ; @PillowPillow

**Comment by PillowPillow** [comment]
Cl

**Pull request closed without merging**
