### PR TITLE
feat: Angular 5.0 compatibility

### PR DESCRIPTION
**Pull request by ryzy**
Makes it compatible with Angular 5. Tested, works in ng5 app and will continue to work on ng4.

`OpaqueToken` was deprecated with v4 and has been completely removed in v5.

If you ok with it, I'll send a sync of `./dist` dir.

Thanks, cheers!

### CODE REVIEW

**Comment by ryzy** [comment]
Also, if you willing to switch to `angular-cli` for dev, I could update whole project to use Angular 5 (i.e. the example app).

**Comment by ryzy** [comment]
Hey @PillowPillow,

I see there's already another PR there with the same. I get you must be busy, but, this one is easy to merge (two lines change + dist) and we're on Angular 5.

**Comment by ryzy** [comment]
PS. If you're looking for help with maintaining this one, happy to help - working full time with Angular, using your package in my company, we like it, so can help at least with minimal maintenance and responding to PRs.

**Comment by aurimukas** [comment]
Agree with @ryzy we should know, if this module is not maintained any more.. we should get someone who checks it more often or do a fork..

**Comment by svitlychnyi** [comment]
+1

**Comment by RasmusTG** [comment]
+1

**Comment by nblavoie** [comment]
@PillowPillow We need this ASAP. Thanks.

**Comment by Gillardo** [comment]
@PillowPillow ?? Can you merge please?

**Comment by mbenzenhoefer** [comment]
+1

**Comment by tommueller** [comment]
+1

**Comment by stas-kh** [comment]
+1

**Comment by nblavoie** [comment]
Can we simply fork the project with the included fixes?

**Comment by svitlychnyi** [comment]
Author is, most probably, just has no time at the moment, but he is active:
Contribution activity: November 7, 2017 (32 contributions in private repositories)

Lets just wait for some time.

**Comment by Gillardo** [comment]
I am just using branch by @ryzy . works perfectly!

**Comment by svitlychnyi** [comment]
Aha, I told you :)

**Comment by Gillardo** [comment]
can you tell us when this will be updated on npm please?

**Comment by nblavoie** [comment]
@Gillardo +1 !

**Comment by abdhafid** [comment]
While waiting for tag, you can use the master code :
`npm install git://github.com/PillowPillow/ng2-webstorage --save`
It's working for me

**Comment by PillowPillow** [comment]
During the night, it will comes with some bug fixes.

**Comment by ryzy** [comment]
@PillowPillow thanks for merging and a new release, great job!

BTW @civicwar agree, the only reason why there were changes in this is because the repo contains also compiled `dist` version of the package and it's the result of whatever `ngc` compiler produces. My change was in one line only :D @PillowPillow might decide at some point to change it (e.g. prepare the dist just for `npm publish` and exclude it from the source code of the repository).

**Comment by PillowPillow** [comment]
I keep the dist in the repo for those that prefers use bower. 
Since i'm not maintaining a bower repo, they can take the sources from github.

**Pull request merged**
